### PR TITLE
Tablefac tests

### PR DESCRIPTION
**Pull request by dominikl**
Fixed some issues with the TableFacility tests. MaskData should work now too. Will probably need https://github.com/ome/omero-gateway-java/pull/58 in order to pass.

### CODE REVIEW

**Comment by jburel** [comment]
```
/src/components/tools/OmeroJava/test/integration/gateway/TablesFacilityTest.java:143: error: cannot find symbol
                    m.setImage(img);
                     ^
  symbol:   method setImage(ImageData)
  location: variable m of type MaskData
/src/components/tools/OmeroJava/test/integration/gateway/TablesFacilityTest.java:151: error: getFile() has private access in FileAnnotationData
                    column[r] = fa.getFile();
```

**Comment by dominikl** [comment]
These are methods which I added to https://github.com/ome/omero-gateway-java/pull/58 . Is it somehow possible to test these PRs together?

**Comment by jburel** [comment]
In order for the PR to be included we will need to modify the github action so it builds the gateway snapshot otherwise the PR will not be included in the build and the tests won't be run

**Comment by dominikl** [comment]
I excluded the MaskData test again. It just doesn't work, and I ran out of ideas now. It works fine in any other context, can store and read MaskData objects from tables, no problem, but just not in context of these integration tests. It throws an `AttributeError: 'MaskColumnI' object has no attribute 'values'` somewhere down the python stack.

**Comment by dominikl** [comment]
I have the suspicion now that the test only fails on my local omero setup. If run the same code as little test example against merge-ci it works. Therefore I added a MaskData test again. Would be interesting to run it as part of the merge build.

**Comment by dominikl** [comment]
Thanks @jburel , tests ran (and are green) in today's build https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/869/testngreports/integration.gateway/TablesFacilityTest/ .

**Pull request merged**
